on:
  push:
    branches:
      - main
      - dev
    # paths:
    #   - "frontend/**"

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git
        run: |
          git config --global user.email "qivaijar@gmail.com"
          git config --global user.name "qivaijar"
      - name: Force Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ vars.HF_USERNAME }}
          SPACE_NAME: ${{ vars.SPACE_NAME }}
        run: |
          # Force push the current state of the branch to the second repo
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main --force
